// <auto-generated />
namespace _2013204637_PER.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class rod12435639685g4 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(rod12435639685g4));
        
        string IMigrationMetadata.Id
        {
            get { return "201706110106024_rod12435639685g4"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
